theme: jekyll-theme-minimal
title: Nicole's Portfolio
description: >
  Fall 2024 digital humanities portfolio.  
  <a href="final_statement.html">Final reflection statement</a> <br>
  <a href="looking_forward.html">What I'm looking forward to</a> <br>
  <a href="ec_reflection.html">Reflection on our time in the EC</a>

